version: '3.1'

services:
  database:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports: 
      - "5433:5432"
    volumes:
      - pgdata:/data/postgres

  backend:
    build: .
    container_name: backend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/backend
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local